# Generated by Django 3.2.8 on 2023-03-28 21:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('times', models.IntegerField(blank=True, null=True)),
                ('max_sp_discount', models.IntegerField(blank=True, null=True)),
                ('one_user', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CouponCodeuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.CharField(max_length=900)),
                ('slug', models.CharField(blank=True, max_length=156, null=True)),
                ('keyword', models.CharField(max_length=156)),
                ('title', models.CharField(max_length=156)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('canonical', models.CharField(default='https://1000gm.org/', max_length=900)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('sold_out', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=156, null=True)),
                ('sp', models.CharField(blank=True, max_length=156, null=True)),
                ('mrp', models.CharField(blank=True, max_length=156, null=True)),
                ('note', models.CharField(blank=True, max_length=156, null=True)),
                ('short_desc', models.TextField(blank=True, max_length=1156, null=True)),
                ('single_piece', models.BooleanField(default=True)),
                ('in_stock', models.IntegerField(blank=True, default=1, null=True)),
                ('review', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('addional_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('img1_alt', models.CharField(blank=True, max_length=156, null=True)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('img2_alt', models.CharField(blank=True, max_length=156, null=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_wishlist', to='shop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Tag'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=101)),
                ('first_name', models.CharField(max_length=310)),
                ('last_name', models.CharField(max_length=310)),
                ('company_name', models.CharField(blank=True, max_length=310, null=True)),
                ('address', models.CharField(max_length=300)),
                ('appartment_no', models.CharField(max_length=130)),
                ('city', models.CharField(max_length=130)),
                ('country', models.CharField(default='INDIA', max_length=1100)),
                ('zip_code', models.CharField(max_length=130)),
                ('coupon_code', models.CharField(blank=True, max_length=1200, null=True)),
                ('discount', models.CharField(blank=True, max_length=200, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('bill', models.TextField(blank=True, max_length=11130, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=11200, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=11200, null=True)),
                ('privacy_policy', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CouponCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.couponcode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CouponCode_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
