# Generated by Django 3.2.8 on 2023-04-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='appartment_no',
        ),
    ]
