# Generated by Django 4.2.2 on 2023-06-23 16:48

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0008_scoholastic"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryProxy",
            fields=[],
            options={
                "verbose_name": "Gallery",
                "verbose_name_plural": "Gallery",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("home.gallery",),
        ),
    ]
