# Generated by Django 4.2.2 on 2023-06-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated", models.DateField(auto_now=True)),
                ("email", models.CharField(max_length=156)),
            ],
        ),
    ]
