# Generated by Django 4.2.2 on 2023-06-23 16:48

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0008_scoholastic"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestVideoFooterProxy",
            fields=[],
            options={
                "verbose_name": "Footer Indisplay Video (max 1)",
                "verbose_name_plural": "Footer Indisplay Video (max 1)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("home.latestvideofooter",),
        ),
        migrations.CreateModel(
            name="LatestVideoProxy",
            fields=[],
            options={
                "verbose_name": "Latest Video",
                "verbose_name_plural": "Latest Videos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("home.latestvideo",),
        ),
        migrations.CreateModel(
            name="VideoTestimonalsProxy",
            fields=[],
            options={
                "verbose_name": "Video Testimonial",
                "verbose_name_plural": "Video Testimonials",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("home.videotestimonals",),
        ),
    ]
