# Generated by Django 3.2 on 2023-06-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_scoholastic'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.CreateModel(
            name='BlogProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.blog',),
        ),
    ]
