# Generated by Django 3.2 on 2023-06-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_scoholastic'),
        ('blog', '0002_auto_20230623_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Blog Author',
                'verbose_name_plural': 'Blog Authors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.author',),
        ),
        migrations.CreateModel(
            name='CategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Category for Blog',
                'verbose_name_plural': 'Category for Blogs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.category',),
        ),
        migrations.CreateModel(
            name='TagsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Tags in Blog',
                'verbose_name_plural': 'Tags in Blogs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.tags',),
        ),
        migrations.AlterModelOptions(
            name='blogproxy',
            options={'verbose_name': '1000gm Blog', 'verbose_name_plural': '1000gm Blogs'},
        ),
    ]
