# Generated by Django 4.2.2 on 2023-06-23 16:48

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0008_scoholastic"),
    ]

    operations = [
        migrations.CreateModel(
            name="ECategoryProxy",
            fields=[],
            options={
                "verbose_name": "Event Category",
                "verbose_name_plural": "Event Category",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("home.ecategory",),
        ),
        migrations.CreateModel(
            name="EventsProxy",
            fields=[],
            options={
                "verbose_name": "All Events",
                "verbose_name_plural": "All Events",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("home.events",),
        ),
    ]
