# Generated by Django 3.2.8 on 2023-04-18 05:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=1256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900)),
                ('keyword', models.CharField(max_length=156)),
                ('title', models.CharField(max_length=156)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('canonical', models.CharField(default='https://website.com/', max_length=900)),
                ('why_choose_us_img', models.ImageField(blank=True, null=True, upload_to='Page Data')),
                ('why_choose_us_img_1', models.ImageField(blank=True, null=True, upload_to='Page Data')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(max_length=156)),
                ('fb', models.CharField(blank=True, max_length=156, null=True)),
                ('insta', models.CharField(blank=True, max_length=156, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=156, null=True)),
                ('image', models.ImageField(upload_to='SEO')),
            ],
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1156)),
                ('venue', models.CharField(max_length=1156)),
                ('date', models.CharField(max_length=1156)),
                ('link', models.CharField(blank=True, max_length=1156, null=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1156)),
                ('email', models.CharField(max_length=1156)),
                ('subject', models.CharField(max_length=1156)),
                ('phone', models.CharField(blank=True, max_length=115, null=True)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('responsded', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('h1', models.CharField(max_length=156)),
                ('slug', models.CharField(blank=True, max_length=1256, null=True)),
                ('keyword', models.CharField(max_length=156)),
                ('description', models.CharField(max_length=900)),
                ('title', models.CharField(max_length=156)),
                ('breadcrumb', models.CharField(max_length=156)),
                ('canonical', models.CharField(default='https://1000gm.org/', max_length=900)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('ads', models.ImageField(blank=True, null=True, upload_to='Ads')),
                ('category', models.CharField(blank=True, max_length=900, null=True)),
                ('label_for_location_1', models.CharField(default='Venue For', max_length=900)),
                ('location1', models.CharField(blank=True, max_length=900, null=True)),
                ('label_for_location_2', models.CharField(blank=True, default='Venue For', max_length=900, null=True)),
                ('location2', models.CharField(blank=True, max_length=900, null=True)),
                ('label_for_location_3', models.CharField(blank=True, default='Venue For', max_length=900, null=True)),
                ('location3', models.CharField(blank=True, max_length=900, null=True)),
                ('label_for_location_4', models.CharField(blank=True, default='Venue For', max_length=900, null=True)),
                ('location4', models.CharField(blank=True, max_length=900, null=True)),
                ('date', models.CharField(blank=True, max_length=900, null=True)),
                ('banner_day', models.CharField(blank=True, max_length=900, null=True)),
                ('banner_month', models.CharField(blank=True, max_length=900, null=True)),
                ('mail', models.CharField(blank=True, max_length=900, null=True)),
                ('phone', models.CharField(blank=True, max_length=900, null=True)),
                ('map_pin', models.CharField(blank=True, max_length=900, null=True)),
                ('updated', models.DateField(auto_now=True)),
                ('published', models.DateField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('edits', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=900, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faqpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1156)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
            ],
        ),
        migrations.CreateModel(
            name='LatestVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1156)),
                ('link', models.CharField(blank=True, max_length=1156, null=True)),
                ('banner_day', models.CharField(blank=True, max_length=900, null=True)),
                ('banner_month', models.CharField(blank=True, max_length=900, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatestVideoFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('link', models.CharField(max_length=156)),
                ('hastag', models.CharField(max_length=156, null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Player Profile')),
                ('name', models.CharField(max_length=1156)),
                ('fide_rating', models.IntegerField()),
                ('fide_id', models.CharField(max_length=1156)),
                ('tournament_played', ckeditor_uploader.fields.RichTextUploadingField()),
                ('federation', models.CharField(blank=True, max_length=900, null=True)),
                ('in_home_page', models.BooleanField(default=False)),
                ('video_url', models.CharField(blank=True, max_length=900, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('h1', models.CharField(max_length=156)),
                ('slug', models.CharField(blank=True, max_length=1256, null=True)),
                ('keyword', models.CharField(max_length=156)),
                ('description', models.CharField(max_length=900)),
                ('title', models.CharField(max_length=156)),
                ('breadcrumb', models.CharField(max_length=156)),
                ('canonical', models.CharField(default='https://1000gm.org/', max_length=900)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(default='https://1000gm.org/', max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('updated', models.DateField(auto_now=True)),
                ('published', models.DateField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1156)),
                ('position', models.CharField(max_length=1156)),
                ('image', models.ImageField(upload_to='TEAM')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SEO')),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(max_length=156)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoTestimonals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('position', models.CharField(default='Dentist', max_length=156)),
                ('video', models.FileField(null=True, upload_to='Testmonials')),
            ],
        ),
        migrations.CreateModel(
            name='EventsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.events')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main3', models.BooleanField(default=False)),
                ('most_visited', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('page_name', models.CharField(blank=True, max_length=1256, null=True)),
                ('h1', models.CharField(max_length=156)),
                ('slug', models.CharField(blank=True, max_length=1256, null=True)),
                ('keyword', models.CharField(max_length=156)),
                ('description', models.CharField(max_length=900)),
                ('title', models.CharField(max_length=156)),
                ('breadcrumb', models.CharField(max_length=156)),
                ('canonical', models.CharField(default='https://thegrandindianroute.com/', max_length=900)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('updated', models.DateField(auto_now=True)),
                ('published', models.DateField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('edits', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.author')),
                ('category', models.ManyToManyField(null=True, to='home.Category')),
                ('tag', models.ManyToManyField(null=True, to='home.Tags')),
            ],
        ),
    ]
