# Generated by Django 3.2.8 on 2023-04-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_events_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecategory',
            name='slug',
            field=models.CharField(blank=True, max_length=156, null=True),
        ),
    ]
