# Generated by Django 3.2.8 on 2023-04-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.CharField(default='someone@1000gm.org', max_length=115),
        ),
    ]
