# Generated by Django 4.2 on 2023-05-15 00:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_playerprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('h1', models.CharField(max_length=156)),
                ('slug', models.CharField(blank=True, max_length=1256, null=True)),
                ('keyword', models.CharField(max_length=156)),
                ('description', models.CharField(max_length=900)),
                ('title', models.CharField(max_length=156)),
                ('breadcrumb', models.CharField(max_length=156)),
                ('canonical', models.CharField(default='https://1000gm.org/', max_length=900)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('ads', models.ImageField(blank=True, null=True, upload_to='Ads')),
                ('category', models.CharField(blank=True, max_length=900, null=True)),
                ('label_for_location_1', models.CharField(default='Venue For', max_length=900)),
                ('location1', models.CharField(blank=True, max_length=900, null=True)),
                ('label_for_location_2', models.CharField(blank=True, default='Venue For', max_length=900, null=True)),
                ('location2', models.CharField(blank=True, max_length=900, null=True)),
                ('label_for_location_3', models.CharField(blank=True, default='Venue For', max_length=900, null=True)),
                ('location3', models.CharField(blank=True, max_length=900, null=True)),
                ('label_for_location_4', models.CharField(blank=True, default='Venue For', max_length=900, null=True)),
                ('location4', models.CharField(blank=True, max_length=900, null=True)),
                ('date', models.CharField(blank=True, max_length=900, null=True)),
                ('banner_day', models.CharField(blank=True, max_length=900, null=True)),
                ('banner_month', models.CharField(blank=True, max_length=900, null=True)),
                ('mail', models.CharField(blank=True, max_length=900, null=True)),
                ('phone', models.CharField(blank=True, max_length=900, null=True)),
                ('map_pin', models.CharField(blank=True, max_length=900, null=True)),
                ('updated', models.DateField(auto_now=True)),
                ('published', models.DateField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('edits', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=900, null=True)),
                ('event_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfileVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='SEO')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ourwork')),
            ],
        ),
    ]
