# Generated by Django 4.2.2 on 2023-06-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_scoholastic"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoholastic",
            name="active",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
