# Generated by Django 4.2.2 on 2023-06-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_scoholastic_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoholastic",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
