# Generated by Django 4.2.2 on 2023-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_scoholastic_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoholastic",
            name="active",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
