# Generated by Django 4.2.2 on 2023-06-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_remove_ourworkimage_work_events_ads_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoholastic",
            name="active",
        ),
        migrations.AddField(
            model_name="scoholastic",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
