# Generated by Django 4.2.2 on 2023-07-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_scoholastic_active_scoholastic_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='link',
            new_name='adv_entry',
        ),
        migrations.AddField(
            model_name='calendar',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='ecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ecategory'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='expected',
            field=models.CharField(blank=True, max_length=1156, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='masters',
            field=models.CharField(blank=True, max_length=1156, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='parings',
            field=models.CharField(blank=True, max_length=1156, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='registration',
            field=models.CharField(blank=True, max_length=1156, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='webpage',
            field=models.CharField(blank=True, max_length=1156, null=True),
        ),
    ]
