# Generated by Django 3.2 on 2023-06-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_scoholastic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBannerImageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Homepage About Us Content (max 3)',
                'verbose_name_plural': 'Homepage About Us Content (max 3)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.aboutbannerimage',),
        ),
        migrations.CreateModel(
            name='BannerImageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Image',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.bannerimage',),
        ),
        migrations.CreateModel(
            name='EventBannerImageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Homepage Event Content (max 3)',
                'verbose_name_plural': 'Homepage Event Content (max 3)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.eventbannerimage',),
        ),
    ]
